apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      releaseName: istio-base
    chart: base
  - repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      valueFiles:
        - >-
          $values/aws/clusters/apps-dev-1/angkor-platform/istio/values.istiod.yaml
      releaseName: istiod
    chart: istiod
  - repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      valueFiles:
        - >-
          $values/aws/clusters/apps-dev-1/angkor-platform/istio/values.istio-cni.yaml
      releaseName: istio-cni
    chart: cni
  - repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.28.1
    helm:
      valueFiles:
        - >-
          $values/aws/clusters/apps-dev-1/angkor-platform/istio/values.ztunnel.yaml
      releaseName: ztunnel
    chart: ztunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      allowEmpty: false
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - kind: DaemonSet
      group: apps
      name: istio-cni-node
      jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name == "install-cni") | .env[] | select(.name == "GOMEMLIMIT") | .valueFrom
        - .spec.template.spec.containers[] | select(.name == "install-cni") | .env[] | select(.name == "GOMAXPROCS") | .valueFrom
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
